apiVersion: apps/v1
kind: Deployment
metadata:
  name: tcc-rabbitmq-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tcc-ampq-rabbitmq
  template:
    metadata:
      name: tcc-ampq-rabbitmq
      labels:
        app: tcc-ampq-rabbitmq
    spec:            
      containers:
        - name: tcc-rabbitmq-pod
          image: rabbitmq:3-management
          env:
          - name: "RABBITMQ_ERLANG_COOKIE"
            value: "1WqgH8N2v1qDBDZDbNy8Bg9IkPWLEpu79m6q+0t36lQ="
          volumeMounts:
          - mountPath: /var/lib/rabbitmq
            name: rabbitmq-data
      volumes:
        - name: rabbitmq-data
          hostPath:
            path: /data/rabbitmq
            type: DirectoryOrCreate