apiVersion: v1
kind: ConfigMap
metadata:
  name: tcc-configmap
data:
  PORT: '8080'
  SPRING_DATASOURCE_URL: jdbc:postgresql://tcc-db-svc.default.svc.cluster.local:5432/tcc_db
  SPRING_DATASOURCE_USERNAME: postgresadmin
  SPRING_DATASOURCE_PASSWORD: admin123
  POSTGRES_DB: tcc_db
  POSTGRES_USER: postgresadmin
  POSTGRES_PASSWORD: admin123  
  RABBIT_ADDRESS: tcc-rabbitmq-svc.default.svc.cluster.local
  RABBIT_PORT: '5672'
  RABBIT_USER: guest
  RABBIT_PASSWORD: guest
  API_OAUTH_ADDRESS: 'http://tcc-auth-api-service.default.svc.cluster.local:8080/oauth'
  API_PROCESSO_INDUSTRIAL_ADDRESS: 'http://tcc-proc-ind-api-service.default.svc.cluster.local:8080/api'
  API_CONSULTORIAS_ASSESSORIAS_ADDRESS: 'http://tcc-consultoria-api-service.default.svc.cluster.local:8080/api'
  API_NORMAS_ADDRESS: 'http://tcc-norma-api-service.default.svc.cluster.local:8080/api'