apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: tcc-proc-ind-api-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: tcc-proc-ind-api-deployment
  minReplicas: 3
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
    