apiVersion: v1
kind: ConfigMap
metadata:
  name: tcc-configmap
data:
  PORT: '8080'
  SPRING_DATASOURCE_URL: jdbc:postgresql://tcc-db-svc.default.svc.cluster.local:5432/tcc_db
  SPRING_DATASOURCE_USERNAME: postgresadmin
  SPRING_DATASOURCE_PASSWORD: admin123
  POSTGRES_DB: tcc_db
  POSTGRES_USER: postgresadmin
  POSTGRES_PASSWORD: admin123  
