apiVersion: v1
kind: Service
metadata:
  name: tcc-rabbitmq-svc
spec:
  type: LoadBalancer
  ports:
    - port: 80
      name: http
      targetPort: 15672  
    - port: 5672
      name: ampq
    - port: 25676
      name: portsext 
  selector:
    app: tcc-ampq-rabbitmq